directories:
  output: D:\1XYX\pro\rush-desktop\out
  buildResources: build
  app: D:\1XYX\pro\rush-desktop\dist
npmRebuild: true
nodeGypRebuild: false
buildDependenciesFromSource: true
productName: rush-desktop
appId: com.dash.rush-desktop
copyright: Copyright © 2022 Dash.All Rights Reserved.
electronDownload:
  cache: C:\Users\Administrator\.electron
  mirror: https://npm.taobao.org/mirrors/electron/
publish:
  - provider: generic
    url: http://update.xieyaxin.top/electron/
nsis:
  oneClick: false
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  allowToChangeInstallationDirectory: true
  perMachine: true
  artifactName: ${productName}_installer_${arch}_${version}(${buildVersion}).${ext}
portable:
  artifactName: ${productName}_portable_${arch}_${version}(${buildVersion}).${ext}
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
  sign: false
  artifactName: ${productName}_mac_${arch}_${version}(${buildVersion}).${ext}
extraResources:
  - from: D:\1XYX\pro\rush-desktop\extra
    to: ''
mac:
  icon: D:\1XYX\pro\rush-desktop\extra\icons\180x180.png
win:
  icon: D:\1XYX\pro\rush-desktop\extra\icons\1024x1024.png
linux:
  icon: D:\1XYX\pro\rush-desktop\extra\icons\1024x1024.png
  artifactName: ${productName}_linux_${arch}_${version}(${buildVersion}).${ext}
  category: Utility
  synopsis: An App for hosts management and switching.
  desktop:
    Name: 0.0.7-beta.6
    Type: Application
    GenericName: An App for hosts management and switching.
files: []
electronVersion: 18.0.3
