// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NiuAdjustWidth: typeof import('./src/componentsAuto/niu-adjust-width/niu-adjust-width.vue')['default']
    NiuScrollbar: typeof import('./src/componentsAuto/niu-scrollbar/niu-scrollbar.vue')['default']
    PsCaptcha: typeof import('princess-ui')['PsCaptcha']
    PsTree: typeof import('princess-ui')['PsTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/componentsAuto/SvgIcon/SvgIcon.vue')['default']
    Tabs: typeof import('./src/componentsAuto/Tabs/Tabs.vue')['default']
  }
}

export {}
